// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.1_db0@0.3.4_drizzle-orm@0.36.4_@types+react@18.3.27_postgres@3.4.7_re_caol2w35fvsay7wwdjpqg22lge/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.2_vite@5.4.21_@types+node@20.19.35_lightningcss@1.27.0_terser@_6heroq5i2vw7syhk32r7webhdm/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}