// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.5.5_magicast@0.5.2_typescript@5.9.3_vue@3.5.29_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.2_vite@5.4.21_@types+node@20.19.35_lightningcss@1.27.0_terser@5.44.1__vue@3.5.29_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.2_vite@5.4.21_@types+node@20.19.35_lightningcss@1.27.0_terser@5.44.1__vue@3.5.29_typescript@5.9.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.2_vite@5.4.21_@types+node@20.19.35_lightningcss@1.27.0_terser@_6heroq5i2vw7syhk32r7webhdm/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.1_@parcel+watcher@2.5.6_@types+node@20.19.35_@vue+compiler-sfc@3.5.29_cac@6.7.14_db_zllc5xczd5d2i7rl3w73fjoy7u/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/pinia")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
