// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/5/2026, 4:07:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/fleetwood/Documents/code/peeps/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/plugins/**/*.{js,ts,mjs}","/Users/fleetwood/Documents/code/peeps/apps/web/composables/**/*.{js,ts,mjs}","/Users/fleetwood/Documents/code/peeps/apps/web/utils/**/*.{js,ts,mjs}","/Users/fleetwood/Documents/code/peeps/apps/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fleetwood/Documents/code/peeps/apps/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;