import { warmPalette } from "./palettes/warm";

export const warmTheme = {
  darkMode: ['selector', '[data-theme="dark"]'],
  name : "Warm",
  icon : "sun",
  fonts: {
    peeps: "Patrick Hand",
    sans : "Merriweather",
    serif: "Fraunces",
    mono : "DM Mono",
  },
  colors: {
    ...warmPalette,
    brand: {
      primary               : "green",
      "primary-foreground"  : "neutral",
      secondary             : "purple",
      "secondary-foreground": "neutral",
      accent                : "orange",
      "accent-foreground"   : "neutral",
      muted                : "neutral.200",
      "muted-foreground"   : "neutral.500",
      page                  : "neutral.100",
      "page-foreground"     : "neutral.900",
    },
    semantic: {
      success             : "green.500",
      "success-foreground": "neutral.50",
      warning             : "yellow.500",
      "warning-foreground": "neutral.50",
      danger              : "red.500",
      "danger-foreground" : "neutral.50",
      info                : "blue.500",
      "info-foreground"   : "purple.100",
    },
    dark: {
      page                  : "neutral.900",
      "page-foreground"     : "neutral.100",
    },
  },
  radii: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
  },
  spacing: {
    0 : 0,
    1 : 4,
    2 : 8,
    3 : 12,
    4 : 16,
    5 : 20,
    6 : 24,
    8 : 32,
    10: 40,
    12: 48,
    16: 64,
    20: 80,
    24: 96,
  },
  typography: {
    fontSize: {
      xs   : 12,
      sm   : 14,
      base : 16,
      lg   : 18,
      xl   : 20,
      "2xl": 24,
      "3xl": 30,
    },
    lineHeight: {
      tight : 1.15,
      snug  : 1.3,
      normal: 1.5,
    },
    fontWeight: {
      normal  : 400,
      medium  : 500,
      semibold: 600,
      bold    : 700,
    },
  },
} as const;
