import { brandPalette } from "./palettes/brand";

export const peepsDark = {
  name : "Peeps Dark",
  icon : "leaf",
  fonts: {
    peeps: "Gluten",
    sans : "Montserrat",
    serif: "Domine",
    mono : "Inconsolata",
  },
  colors: {
    ...brandPalette,
    brand: {
      primary               : "gold.DEFAULT",
      "primary-foreground"  : "neutral.50",
      secondary             : "green.DEFAULT",
      "secondary-foreground": "neutral.50",
      accent                : "blue.DEFAULT",
      "accent-foreground"   : "neutral.50",
      muted                : "neutral.900",
      "muted-foreground"   : "neutral.500",
      page                  : "green.900",
      "page-foreground"     : "neutral.100",
    },
    semantic: {
      success             : "green.500",
      "success-foreground": "neutral.50",
      warning             : "orange.500",
      "warning-foreground": "neutral.50",
      danger              : "red.500",
      "danger-foreground" : "neutral.50",
      info                : "purple.500",
      "info-foreground"   : "purple.100",
    },
  },
  radii: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
  },
  spacing: {
    0 : 0,
    1 : 4,
    2 : 8,
    3 : 12,
    4 : 16,
    5 : 20,
    6 : 24,
    8 : 32,
    10: 40,
    12: 48,
    16: 64,
    20: 80,
    24: 96,
  },
  typography: {
    fontSize: {
      xs   : 12,
      sm   : 14,
      base : 16,
      lg   : 18,
      xl   : 20,
      "2xl": 24,
      "3xl": 30,
    },
    lineHeight: {
      tight : 1.15,
      snug  : 1.3,
      normal: 1.5,
    },
    fontWeight: {
      normal  : 400,
      medium  : 500,
      semibold: 600,
      bold    : 700,
    },
  },
} as const
